version: "3"

networks:
  payments:

services:
  nginx:
    container_name: "store_nginx"
    image: nginx:stable-alpine
    networks:
      - payments
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php

  php:
    container_name: "store_php"
    networks:
      - payments
    build:
      context: .
      dockerfile: dockerfiles/php2.dockerfile
    volumes:
      - ./src:/var/www/html

